---
# Users module config (Calamares 3.4 schema)

user:
    shell: /usr/bin/zsh

defaultGroups:
    - users
    - video
    - wheel
    - audio
    - input
    - power
    - network
    - storage
    - lp
    - optical
    - i2c

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true
doReusePassword: true
allowWeakPasswords: false

passwordRequirements:
    minLength: -1
    maxLength: -1
    libpwquality:
        - minlen=0
        - minclass=0
