keep-open=yes

vo=gpu
hwdec=auto-copy
vd-lavc-dr=no

cache=yes
cache-secs=60
demuxer-readahead-secs=20   # preload more

osc=yes
border=yes
cursor-autohide=1000
script-opts=thumbfast-scalewidth=200
volume=50
volume-max=200
osd-bar=yes
geometry=60%x60%
autofit-larger=90%x90%
